import {initializeApp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import {getAuth,onAuthStateChanged,signInAnonymously,signOut} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {getFirestore,collection,doc,getDoc,getDocs,query,where,orderBy,limit,runTransaction,serverTimestamp,increment,setDoc,addDoc,updateDoc} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import {getStorage,ref,uploadBytes,getDownloadURL} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js";
import {firebaseConfig} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],fmt=n=>Number(n||0).toLocaleString("ja-JP");
const fallback={water:{id:"water",name:"十万円の水",price:10000,stock:15,image:"Goods/water.svg",description:"高級トプマネ出汁入り。"},penlight:{id:"penlight",name:"ペンライト",price:100,stock:15,image:"Goods/penlight.svg",description:"デコれます！"}};
const state={user:null,profile:null,items:fallback,listings:[],rate:148.532,history:[],lev:2,pos:null};
function toast(t,m=""){let e=document.createElement("div");e.className="toast";e.innerHTML="<b>"+t+"</b>"+m;$("#toasts").append(e);setTimeout(()=>e.remove(),3200)}
function tab(n){$$(".page").forEach(x=>x.classList.remove("active"));$("#"+n)?.classList.add("active");$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.tab===n))}
$$("[data-tab]").forEach(x=>x.onclick=()=>tab(x.dataset.tab));$("#balanceBtn").onclick=()=>tab("account");$("#accountBtn").onclick=()=>tab("account");
$("#openTicker").onclick=()=>{$("#tickerSmall").hidden=true;$("#tickerLarge").hidden=false};$("#closeTicker").onclick=()=>{$("#tickerLarge").hidden=true;$("#tickerSmall").hidden=false};
function status(s){return({admin:"管理者",fan:"一般ファン",fanclub:"ファンクラブ",staff:"スタッフ",member:"メンバー"})[s]||"一般ファン"}
function sync(){let p=state.profile||{displayName:"ゲスト",status:"fan",balance:15000,fcPaid:0};$("#userName").textContent=p.displayName;$("#accountName").textContent=p.displayName;$("#status").textContent=status(p.status);$("#accountStatus").textContent=status(p.status);$("#homeStatus").textContent=status(p.status);$("#balance").textContent=fmt(p.balance);$("#homeBalance").textContent=fmt(p.balance)+" $s";$("#accountBalance").textContent=fmt(p.balance)+"$s";$("#avatar").textContent=(p.displayName||"G")[0];$("#paid").textContent=fmt(p.fcPaid)+"$s";$("#remaining").textContent=fmt(Math.max(0,2000-(p.fcPaid||0)))+"$s";$("#fcProgress").style.width=Math.min(100,(p.fcPaid||0)/20)+"%";$("#joinPanel").style.display=p.status==="fanclub"?"none":"block";$("#admin").hidden=p.status!=="admin"}
async function profile(u){let d=doc(db,"users",u.uid),s=await getDoc(d);if(!s.exists())await setDoc(d,{displayName:"ファン",status:"fan",balance:15000,fcPaid:0,createdAt:serverTimestamp()});state.profile=(await getDoc(d)).data();sync()}
async function items(){try{let s=await getDocs(collection(db,"items"));if(s.size){state.items={};s.forEach(d=>state.items[d.id]={id:d.id,...d.data()})}}catch(e){}renderShop()}
function renderShop(){$("#shopGrid").innerHTML=Object.values(state.items).map(i=>`<article class="product"><div class="product-img"><img src="${i.image}" onerror="this.style.display='none'"></div><div class="product-body"><h3>${i.name}</h3><div class="price">${fmt(i.price)} $s</div><div class="stock">毎日15個 / 残り ${i.stock??15}個</div><p>${i.description||""}</p><button class="primary" data-buy="${i.id}">購入する</button></div></article>`).join("");$$("[data-buy]").forEach(b=>b.onclick=()=>buyOfficial(b.dataset.buy))}
async function buyOfficial(id){let i=state.items[id];try{await runTransaction(db,async t=>{let u=doc(db,"users",state.user.uid),g=doc(db,"items",id),us=await t.get(u),gs=await t.get(g);if(!us.exists()||!gs.exists())throw Error("商品データがありません");let p=us.data(),x=gs.data();if((p.balance||0)<x.price)throw Error("$sが足りません");if((x.stock??0)<=0)throw Error("在庫切れです");t.update(u,{balance:increment(-x.price)});t.update(g,{stock:increment(-1)});t.set(doc(collection(db,"transactions")),{type:"official_purchase",buyerId:state.user.uid,itemId:id,price:x.price,status:"completed",createdAt:serverTimestamp()})});toast("購入しました",i.name+" / "+fmt(i.price)+" $s");}catch(e){toast("購入できません",e.message)}}
async function market(){try{let s=await getDocs(query(collection(db,"listings"),where("status","==","active"),orderBy("createdAt","desc"),limit(60)));state.listings=s.docs.map(d=>({id:d.id,...d.data()}))}catch(e){state.listings=[]}renderMarket()}
function renderMarket(){let q=($("#marketSearch").value||"").toLowerCase();let a=state.listings.filter(x=>(x.name+" "+x.description+" "+(x.hashtags||[]).join(" ")).toLowerCase().includes(q));$("#marketGrid").innerHTML=a.length?a.map(x=>`<article class="market-card"><div class="market-thumb"><img src="${x.thumbnailUrl}" alt=""></div><div class="body"><h3>${x.name}</h3><div class="seller">${x.sellerName||"出品者"}</div><div class="price">${fmt(x.price)} $s</div><p>${x.description||""}</p><div class="tags">${(x.hashtags||[]).map(t=>`<span class="tag">#${t}</span>`).join("")}</div><button class="primary" data-marketbuy="${x.id}">購入する</button></div></article>`).join(""):`<p class="hint">該当する出品がありません。</p>`;$$("[data-marketbuy]").forEach(b=>b.onclick=()=>buyListing(b.dataset.marketbuy));let ts=[...new Set(state.listings.flatMap(x=>x.hashtags||[]))];$("#tags").innerHTML=ts.slice(0,20).map(t=>`<button data-tag="${t}">#${t}</button>`).join("");$$("[data-tag]").forEach(b=>b.onclick=()=>{$("#marketSearch").value=b.dataset.tag;renderMarket()})}
$("#marketSearch").oninput=renderMarket;$("#clearSearch").onclick=()=>{$("#marketSearch").value="";renderMarket()};
function sellModal(){$("#modalBack").hidden=false;$("#modal").innerHTML=`<button class="modal-close" id="mc">×</button><h2>物を売る</h2><div class="form-grid"><label>商品画像<input class="field" id="img" type="file" accept="image/png,image/jpeg,image/webp"></label><label>商品名<input class="field" id="name"></label><label>価格（$s）<input class="field" id="price" type="number" min="1"></label><label>説明<textarea class="field" id="desc"></textarea></label><label>ハッシュタグ<input class="field" id="hashtags" placeholder="#ペンライト #レア #並木"></label><button class="primary" id="submit">出品する</button></div>`;$("#mc").onclick=()=>$("#modalBack").hidden=true;$("#submit").onclick=submitSell}
$("#sellOpen").onclick=sellModal;
async function submitSell(){let f=$("#img").files[0],n=$("#name").value.trim(),p=Math.floor(Number($("#price").value));if(!f||!n||!p)return toast("入力不足","画像・商品名・価格を入力してください");if(f.size>5*1024*1024)return toast("画像が大きすぎます","5MB以下にしてください");try{let path=`market/${state.user.uid}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await uploadBytes(ref(storage,path),f,{contentType:f.type});let url=await getDownloadURL(ref(storage,path));await addDoc(collection(db,"listings"),{sellerId:state.user.uid,sellerName:state.profile.displayName,name:n,price:p,description:$("#desc").value,hashtags:$("#hashtags").value.split(/\s+/).filter(Boolean).map(x=>x.replace(/^#/,"")),thumbnailUrl:url,storagePath:path,status:"active",createdAt:serverTimestamp()});$("#modalBack").hidden=true;toast("出品しました");market()}catch(e){toast("出品できません",e.message)}}
async function buyListing(id){let l=state.listings.find(x=>x.id===id);if(!l)return;let code="TM-"+crypto.randomUUID().replaceAll("-","").slice(0,12).toUpperCase();try{await runTransaction(db,async t=>{let u=doc(db,"users",state.user.uid),li=doc(db,"listings",id),us=await t.get(u),ls=await t.get(li);if(!ls.exists()||ls.data().status!=="active")throw Error("売り切れです");let x=ls.data();if(x.sellerId===state.user.uid)throw Error("自分の商品は購入できません");if((us.data().balance||0)<x.price)throw Error("$sが足りません");let seller=doc(db,"users",x.sellerId),ss=await t.get(seller);if(!ss.exists())throw Error("出品者が見つかりません");let tax=Math.floor(x.price*.07),ship=Math.floor(x.price*.02);t.update(u,{balance:increment(-x.price)});t.update(seller,{balance:increment(x.price-tax-ship)});t.update(li,{status:"sold",buyerId:state.user.uid,transactionCode:code,soldAt:serverTimestamp()});t.set(doc(collection(db,"transactions")),{type:"market_sale",listingId:id,buyerId:state.user.uid,sellerId:x.sellerId,price:x.price,tax,shipping:ship,sellerReceive:x.price-tax-ship,code,status:"completed",createdAt:serverTimestamp()})});toast("購入完了","取引コード："+code);market()}catch(e){toast("購入できません",e.message)}}
const c=$("#chart"),ctx=c.getContext("2d");function chart(){let w=c.clientWidth||600,h=250,d=state.history.length?state.history:[148.2,148.5,148.3,148.7,148.4,148.6,148.5,148.8,148.4,148.532];c.width=w*devicePixelRatio;c.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,w,h);let mi=Math.min(...d)-.2,ma=Math.max(...d)+.2;ctx.beginPath();d.forEach((v,i)=>{let x=i*w/(d.length-1),y=h-(v-mi)/(ma-mi)*h*.78-h*.1;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle="#b48a2a";ctx.lineWidth=2;ctx.stroke()}
function fx(){state.rate=Math.max(100,Math.min(200,state.rate+(Math.random()-.5)*.18));state.history.push(state.rate);state.history=state.history.slice(-40);let ch=(state.rate/state.history[0]-1)*100;$("#fxRate").textContent=state.rate.toFixed(3);$("#fxRate2").textContent=state.rate.toFixed(3);$("#tickerRate").textContent="TOP/JPY "+state.rate.toFixed(3);$("#tickerRate2").textContent=state.rate.toFixed(3);$("#fxChange").textContent=(ch>=0?"+":"")+ch.toFixed(2)+"%";$("#tickerChange").textContent=(ch>=0?"+":"")+ch.toFixed(2)+"%";chart();position()}
function position(){let p=state.pos;if(!p){$("#position").className="position empty";$("#position").textContent="ポジションはありません。";$("#risk").textContent="通常";return}let mv=p.side==="buy"?state.rate-p.entry:p.entry-state.rate,pnl=Math.floor(mv/p.entry*p.stake*p.lev),ratio=Math.max(0,100+pnl/p.stake*100);$("#position").className="position";$("#position").innerHTML=`<b>${p.side==="buy"?"▲ BUY":"▼ SELL"} ${p.lev}x</b><div>約定 ${p.entry.toFixed(3)} / 掛金 ${fmt(p.stake)}$s</div><div>含み損益 <b>${pnl>=0?"+":""}${fmt(pnl)}$s</b></div><small>証拠金維持率の目安 ${ratio.toFixed(1)}%</small><br><button class="primary" id="closeFx">決済する</button>`;$("#risk").textContent=ratio<35?"ロスカット警戒":ratio<55?"注意":"通常";$("#closeFx").onclick=closeFx}
function openFx(side){let s=Math.floor(Number($("#stake").value));if(state.pos)return toast("取引中","先に決済してください");if(!s||s<1)return toast("入力エラー");if((state.profile?.balance||0)<s)return toast("$sが足りません");state.pos={side,stake:s,entry:state.rate,lev:state.lev};toast("ポジション開始",side==="buy"?"買い":"売り");position()}
async function closeFx(){let p=state.pos,m=p.side==="buy"?state.rate-p.entry:p.entry-state.rate,pnl=Math.floor(m/p.entry*p.stake*p.lev),pay=Math.max(0,p.stake+pnl);try{await updateDoc(doc(db,"users",state.user.uid),{balance:increment(pay)});await addDoc(collection(db,"fxTransactions"),{userId:state.user.uid,side:p.side,stake:p.stake,leverage:p.lev,entry:p.entry,exit:state.rate,pnl,payout:pay,createdAt:serverTimestamp()});state.pos=null;toast("決済完了",(pnl>=0?"+":"")+fmt(pnl)+" $s");position()}catch(e){toast("決済エラー",e.message)}}
$$(".levs button").forEach(b=>b.onclick=()=>{$$(".levs button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.lev=Number(b.dataset.lev)});
$("#fxBuy").onclick=()=>openFx("buy");$("#fxSell").onclick=()=>openFx("sell");
$("#fcPay").onclick=async()=>{let a=Math.floor(Number($("#fcAmount").value)),p=state.profile,r=Math.max(0,2000-(p.fcPaid||0));if(!a||a>r)return toast("支払いエラー","残りの会費以内で入力してください");if((p.balance||0)<a)return toast("$sが足りません");try{await runTransaction(db,async t=>{let u=doc(db,"users",state.user.uid),s=await t.get(u);if((s.data().balance||0)<a)throw Error("$sが足りません");t.update(u,{balance:increment(-a),fcPaid:increment(a)});t.set(doc(collection(db,"transactions")),{type:"fc_fee",userId:state.user.uid,amount:a,createdAt:serverTimestamp()})});$("#fcAmount").value="";toast("会費を支払いました",fmt(a)+" $s")}catch(e){toast("支払いエラー",e.message)}};
$("#fcJoin").onclick=async()=>{let code=$("#fcCode").value.trim();try{await runTransaction(db,async t=>{let c=doc(db,"fcCodes",code),u=doc(db,"users",state.user.uid),cs=await t.get(c),us=await t.get(u);if(!cs.exists()||cs.data().active!==true||(cs.data().uses||0)>=(cs.data().maxUses||1))throw Error("無効な入会コードです");t.update(c,{uses:increment(1)});t.update(u,{status:"fanclub"})});toast("ドルズへようこそ")}catch(e){toast("入会できません",e.message)}};
$("#logout").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{if(!u){try{await signInAnonymously(auth)}catch(e){toast("Firebase設定が必要です",e.message)}return}state.user=u;await profile(u);await items();await market();sync()});
setInterval(fx,2500);window.addEventListener("resize",chart);