import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{getFirestore,collection,doc,getDoc,getDocs,query,where,orderBy,limit,onSnapshot,runTransaction,setDoc,updateDoc,addDoc,serverTimestamp,increment}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import{getStorage,ref,uploadBytes,getDownloadURL}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js";
import{firebaseConfig}from"./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],yen=n=>Number(n||0).toLocaleString("ja-JP");
const ITEMS={water:{name:"十万円の水",image:"Goods/water.svg",emoji:"💧",base:10000,vol:.2},penlight:{name:"ペンライト",image:"Goods/penlight.svg",emoji:"🪄",base:100,vol:.1}};
const NEWS_DATA=[
{date:"9月18日",title:"握手会開催のお知らせ",text:"ライブ後に握手会を開催いたします。参加には1000$sが必要です。撮影可ですがSNSへのアップロードはご遠慮ください。"},
{date:"9月11日",title:"初ライブ開催決定",text:"6年4組にてクラブ風ステージを開催します。皆様のご来場をお待ちしております。"},
{date:"9月4日",title:"トプマネ デビュー",text:"話題沸騰中のアイドルグループ「Top of the Money」が本日デビューしました。応援よろしくお願いいたします。"}];
let state={user:null,profile:null,inventory:[],market:[],prices:{water:10000,penlight:100},stock:{water:15,penlight:15},bankSupply:1000000,marketHistory:{fx:[],water:[],penlight:[]},fx:{rate:148,position:null,leverage:2},decorated:{},heat:0,contribution:0,activeModalItem:null};

function toast(t,m=""){let s=$("#toast-stack");if(!s){s=document.createElement("div");s.id="toast-stack";s.className="toast-stack";document.body.appendChild(s)}let x=document.createElement("div");x.className="toast";x.innerHTML=`<strong>${t}</strong><div>${m}</div>`;s.appendChild(x);setTimeout(()=>x.remove(),3200)}
function statusLabel(s){return({admin:"管理者",fan:"一般ファン",fanclub:"ファンクラブ",staff:"スタッフ",member:"メンバー"})[s]||"一般ファン"}
function switchTab(id){$$(".tab-content").forEach(x=>x.classList.remove("active"));$("#tab-"+id)?.classList.add("active");$$(".tab-btn").forEach(x=>x.classList.toggle("active",x.dataset.tab===id));if(id==="inventory")renderInventory();if(id==="room")renderRoom();if(id==="market")renderMarket()}
window.switchTab=switchTab;
$$(".tab-btn").forEach(x=>x.addEventListener("click",()=>switchTab(x.dataset.tab)));
$("#ticker-open")?.addEventListener("click",()=>$("#ticker-expanded").hidden=false);
$("#ticker-close")?.addEventListener("click",()=>$("#ticker-expanded").hidden=true);

function renderNews(){let latest=NEWS_DATA[0],a=$("#home-latest-news"),b=$("#news-list-container");if(a)a.innerHTML=`<div class="news-date">${latest.date}</div><div class="news-title">${latest.title}</div><div class="news-text">${latest.text}</div>`;if(b)b.innerHTML=NEWS_DATA.map(n=>`<article class="news-box"><div class="news-date">${n.date}</div><div class="news-title">${n.title}</div><div class="news-text">${n.text}</div></article>`).join("")}
function sync(){let p=state.profile||{displayName:"GUEST",status:"fan",balance:15000,fcPaid:0};$("#pt-display").textContent=yen(p.balance);$("#user-name").textContent=p.displayName;$("#head-role").textContent=statusLabel(p.status);$("#set-name-input")&&($("#set-name-input").value=p.displayName);$("#set-role-display")&&($("#set-role-display").textContent=statusLabel(p.status));$("#account-cover-status")&&($("#account-cover-status").textContent=statusLabel(p.status));$("#account-display-name")&&($("#account-display-name").textContent=p.displayName);$("#account-status")&&($("#account-status").textContent=statusLabel(p.status));$("#profile-avatar")&&($("#profile-avatar").textContent=(p.displayName||"G")[0].toUpperCase());$("#account-balance")&&($("#account-balance").textContent=yen(p.balance)+" $s");$("#home-latest-news")&&0;$("#admin-menu-item")&&($("#admin-menu-item").style.display=p.status==="admin"?"block":"none");$("#admin-status")&&($("#admin-status").textContent=statusLabel(p.status));renderFC();renderTicker()}
async function ensureProfile(u){let r=doc(db,"users",u.uid),s=await getDoc(r);if(!s.exists())await setDoc(r,{displayName:u.email?.split("@")[0]||"ドルズ",status:"fan",balance:15000,fcPaid:0,createdAt:serverTimestamp()});state.profile=(await getDoc(r)).data();sync();onSnapshot(r,x=>{if(x.exists()){state.profile=x.data();sync()}})}
function renderFC(){let paid=state.profile?.fcPaid||0,remain=Math.max(0,2000-paid);$("#fc-role")&&($("#fc-role").textContent=statusLabel(state.profile.status));$("#fc-member-name")&&($("#fc-member-name").textContent=state.profile.displayName);if($("#fc-unregistered"))$("#fc-unregistered").style.display=state.profile.status==="fanclub"?"none":"block";if($("#fc-registered"))$("#fc-registered").style.display=state.profile.status==="fanclub"?"block":"none"}

function wave(t,base,vol,a,b,c){return base+base*vol*((Math.sin(t*a)*1.5+Math.cos(t*b)+Math.sin(t*c)*.8+Math.cos(t*(a+b))*.5+Math.sin(t*1.7)*Math.cos(t*2.1)*.4)/4.2)}
function updatePrices(){let t=Math.floor(Date.now()/1000);state.prices.water=Math.max(1,Math.floor(wave(t,10000,.2,.011,.033,.077)*(1+(15-state.stock.water)*.008)));state.prices.penlight=Math.max(1,Math.floor(wave(t,100,.1,.045,.088,.19)*(1+(15-state.stock.penlight)*.01)));$("#list-price-water")&&($("#list-price-water").textContent=yen(state.prices.water));$("#list-price-penlight")&&($("#list-price-penlight").textContent=yen(state.prices.penlight));$("#ticker-water").textContent=yen(state.prices.water)+" $s";$("#ticker-penlight").textContent=yen(state.prices.penlight)+" $s";$("#ticker-water-stock").textContent=`本日残り${state.stock.water}個`;$("#ticker-penlight-stock").textContent=`本日残り${state.stock.penlight}個`}
function chart(id,data,color){let c=$(id);if(!c||!data.length)return;let r=c.getBoundingClientRect(),w=Math.max(260,r.width),h=c.height||230,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;let x=c.getContext("2d");x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);let mi=Math.min(...data),ma=Math.max(...data),rg=ma-mi||1;x.beginPath();x.strokeStyle=color;x.lineWidth=2.2;data.forEach((v,i)=>{let px=i*w/(data.length-1),py=h-((v-mi)/rg)*(h-25)-12;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
function initHistory(){let now=Math.floor(Date.now()/1000);state.marketHistory={fx:[],water:[],penlight:[]};for(let i=60;i>=0;i--){let t=now-i;state.marketHistory.fx.push(wave(t,148,.03,.02,.05,.1));state.marketHistory.water.push(Math.floor(wave(t,10000,.2,.011,.033,.077)));state.marketHistory.penlight.push(Math.floor(wave(t,100,.1,.045,.088,.19)))}state.fx.rate=state.marketHistory.fx.at(-1)}
function tick(){let t=Math.floor(Date.now()/1000),fx=wave(t,148,.03,.02,.05,.1),wat=Math.floor(wave(t,10000,.2,.011,.033,.077)),pen=Math.floor(wave(t,100,.1,.045,.088,.19));state.fx.rate=fx;state.marketHistory.fx.push(fx);state.marketHistory.fx.shift();state.marketHistory.water.push(wat);state.marketHistory.water.shift();state.marketHistory.penlight.push(pen);state.marketHistory.penlight.shift();let first=state.marketHistory.fx[0],chg=(fx/first-1)*100;$("#ticker-current").textContent=`TOP/JPY ${fx.toFixed(3)}`;$("#ticker-fx").textContent=fx.toFixed(3);$("#ticker-fx-change").textContent=`${chg>=0?"+":""}${chg.toFixed(2)}%`;$("#fx-rate-display")&&($("#fx-rate-display").textContent=fx.toFixed(3));chart("#fxChart",state.marketHistory.fx,"#4ade80");renderFXPosition();updatePrices()}
function openShopModal(id){state.activeModalItem=id;$("#modal-item-icon").textContent=ITEMS[id].emoji;$("#modal-item-name").textContent=ITEMS[id].name;$("#modal-item-price").textContent=yen(state.prices[id])+" $s";$("#shop-modal").style.display="flex";chart("#modal-chart",state.marketHistory[id],"#eab308");updateBuyButton()}
function updateBuyButton(){let id=state.activeModalItem;if(!id)return;let b=$("#modal-buy-btn"),p=state.prices[id];b.disabled=(state.profile?.balance||0)<p||state.stock[id]<=0;$("#modal-error-msg").style.display=b.disabled?"block":"none";$("#modal-error-msg").textContent=state.stock[id]<=0?"本日の在庫がありません":(state.profile?.balance||0)<p?"$sが足りません":""}
window.openShopModal=openShopModal;window.closeShopModal=()=>{$("#shop-modal").style.display="none";state.activeModalItem=null};window.executeBuy=async()=>{let id=state.activeModalItem,p=state.prices[id];if(!id||state.stock[id]<=0||(state.profile?.balance||0)<p)return;try{await runTransaction(db,async tx=>{let u=doc(db,"users",state.user.uid),i=doc(db,"items",id),us=await tx.get(u),is=await tx.get(i);let bal=us.data().balance||0,stock=is.exists()?(is.data().stock??15):state.stock[id];if(bal<p)throw Error("$sが足りません");if(stock<=0)throw Error("在庫切れです");tx.update(u,{balance:increment(-p)});if(is.exists())tx.update(i,{stock:increment(-1)});tx.set(doc(collection(db,"transactions")),{type:"official_purchase",buyerId:state.user.uid,itemId:id,price:p,status:"completed",createdAt:serverTimestamp()})});state.profile.balance-=p;state.stock[id]--;sync();updateBuyButton();toast("購入完了",`${ITEMS[id].name} / ${yen(p)} $s`)}catch(e){toast("購入できません",e.message)}};

function renderInventory(){let list=$("#inventory-list");if(!list)return;if(!state.inventory.length){list.innerHTML='<p style="color:var(--text-sub)">アイテムがありません。</p>';return}let groups={water:[],penlight:[]};state.inventory.forEach(x=>groups[x.id]?.push(x));list.innerHTML=Object.entries(groups).filter(([,a])=>a.length).map(([id,a])=>`<div class="inv-group"><div class="inv-group-title">${ITEMS[id].emoji} ${ITEMS[id].name}（所持 ${a.length}）</div><button class="btn btn-sell-all" onclick="sellAll('${id}')">このアイテムをすべて売却</button>${a.map(i=>`<div class="inv-item"><div class="inv-details"><div class="inv-line">購入価格：${yen(i.buyPrice)} $s</div><div class="inv-line">現在の市場価値：${yen(state.prices[id])} $s</div><div class="inv-tax">トプマネ税 7% / 送料 2%</div><div class="inv-final">想定受取額：${yen(Math.floor(state.prices[id]*.91))} $s</div></div><button class="btn btn-danger" onclick="sellItem('${i.uid}')">売る</button></div>`).join("")}</div>`).join("")}
window.sellItem=uid=>{let i=state.inventory.find(x=>String(x.uid)===String(uid));if(!i)return;let r=Math.floor(state.prices[i.id]*.91);state.inventory=state.inventory.filter(x=>String(x.uid)!==String(uid));state.profile.balance+=r;sync();renderInventory();renderRoom();toast("売却",`${yen(r)} $sを受け取りました。`)};
window.sellAll=id=>{let n=state.inventory.filter(x=>x.id===id).length;if(!n)return;let r=Math.floor(state.prices[id]*.91)*n;state.inventory=state.inventory.filter(x=>x.id!==id);state.profile.balance+=r;sync();renderInventory();renderRoom();toast("一括売却",`${yen(r)} $sを受け取りました。`)};

function renderRoom(){let s=$("#room-shelf");if(!s)return;s.innerHTML=Object.keys(ITEMS).map(id=>{let n=state.inventory.filter(x=>x.id===id).length;if(!n)return"";let d=state.decorated[id]||0;return`<div class="room-item ${d?"decorated":""}"><div class="room-icon"><img src="${ITEMS[id].image}" style="width:70px;height:70px;object-fit:contain"></div><strong>${ITEMS[id].name}</strong><div style="font-size:11px;color:var(--text-sub)">所持 ${n} / 飾り ${d}</div><button class="btn" onclick="toggleDecoration('${id}')">${d?"片付ける":"飾る"}</button></div>`}).join("")||'<div style="grid-column:1/-1;text-align:center;color:var(--text-sub);padding:30px">まずショップでグッズを購入してください。</div>';updateRoomStats()}
function updateRoomStats(){let u=Object.values(state.decorated).reduce((a,b)=>a+b,0);state.fanPower=u*10+Object.keys(state.decorated).length*15+Math.floor(state.contribution/100);let title="新米ドルズ",rank=1;if(state.fanPower>=120){title="伝説のコレクター";rank=5}else if(state.fanPower>=70){title="超本気ドルズ";rank=4}else if(state.fanPower>=35){title="熱烈コレクター";rank=3}else if(state.fanPower>=15){title="コレクター見習い";rank=2}$("#fan-power")&&($("#fan-power").textContent=state.fanPower);$("#contribution")&&($("#contribution").textContent=yen(state.contribution)+" $s");$("#collector-title")&&($("#collector-title").textContent=title);$("#title-rank")&&($("#title-rank").textContent=rank);$("#fan-progress")&&($("#fan-progress").style.width=Math.min(100,(state.fanPower%35)/35*100)+"%");$("#heat-value")&&($("#heat-value").textContent=Math.floor(state.heat));$("#heat-progress")&&($("#heat-progress").style.width=Math.min(100,state.heat)+"%")}
window.toggleDecoration=id=>{state.decorated[id]=state.decorated[id]?0:state.inventory.filter(x=>x.id===id).length;renderRoom()};window.decorateAllOwned=()=>{Object.keys(ITEMS).forEach(id=>{let n=state.inventory.filter(x=>x.id===id).length;if(n)state.decorated[id]=n});renderRoom();toast("推し部屋","所持グッズを展示しました。")};window.useMerch=id=>{if(!state.inventory.some(x=>x.id===id))return toast("グッズがありません","まずショップで購入してください。");state.heat=Math.min(100,state.heat+(id==="penlight"?12:5));$("#room-message").textContent=id==="penlight"?"ペンライトが光った！会場の熱気が上昇！":"十万円の水をじっと眺めた。";updateRoomStats()};

async function loadMarket(){try{let q=await getDocs(query(collection(db,"listings"),where("status","==","active"),orderBy("createdAt","desc"),limit(60)));state.market=q.docs.map(d=>({id:d.id,...d.data()}))}catch(e){state.market=[]}renderMarket()}
function renderMarket(){let q=($("#market-search")?.value||"").trim().toLowerCase(),a=state.market.filter(x=>`${x.name||""} ${x.description||""} ${(x.hashtags||[]).join(" ")}`.toLowerCase().includes(q));$("#market-count")&&($("#market-count").textContent=a.length);$("#market-list").innerHTML=a.length?a.map(x=>`<article class="market-item-card"><div class="market-thumb"><img src="${x.thumbnailUrl||""}" alt=""></div><div class="market-body"><h3>${x.name}</h3><div class="market-seller">${x.sellerName||"出品者"}</div><div class="market-price">${yen(x.price)} $s</div><p style="font-size:12px;color:var(--text-sub);line-height:1.6">${x.description||""}</p><div class="market-tags">${(x.hashtags||[]).map(t=>`<span>#${t}</span>`).join("")}</div><button class="btn market-buy" data-id="${x.id}">購入する</button></div></article>`).join(""):'<div style="color:var(--text-sub);padding:30px;text-align:center">現在、出品中の商品はありません。</div>';$$(".market-buy").forEach(b=>b.onclick=()=>buyListing(b.dataset.id));$("#market-tags").innerHTML=[...new Set(state.market.flatMap(x=>x.hashtags||[]))].slice(0,20).map(t=>`<button class="market-tag" data-tag="${t}">#${t}</button>`).join("");$$("[data-tag]").forEach(b=>b.onclick=()=>{$("#market-search").value=b.dataset.tag;renderMarket()})}
async function buyListing(id){let l=state.market.find(x=>x.id===id);if(!l)return;let code=`TM-${crypto.randomUUID().replaceAll("-","").slice(0,4).toUpperCase()}-${crypto.randomUUID().replaceAll("-","").slice(0,8).toUpperCase()}`;try{await runTransaction(db,async tx=>{let b=doc(db,"users",state.user.uid),li=doc(db,"listings",id),bs=await tx.get(b),ls=await tx.get(li);if(!ls.exists()||ls.data().status!=="active")throw Error("売り切れまたは終了しています");let x=ls.data();if(x.sellerId===state.user.uid)throw Error("自分の出品は購入できません");if((bs.data().balance||0)<x.price)throw Error("$sが足りません");let s=doc(db,"users",x.sellerId),ss=await tx.get(s);if(!ss.exists())throw Error("出品者が見つかりません");let tax=Math.floor(x.price*.07),shipping=Math.floor(x.price*.02);tx.update(b,{balance:increment(-x.price)});tx.update(s,{balance:increment(x.price-tax-shipping)});tx.update(li,{status:"sold",buyerId:state.user.uid,transactionCode:code,soldAt:serverTimestamp()});tx.set(doc(collection(db,"transactions")),{type:"market_sale",listingId:id,buyerId:state.user.uid,sellerId:x.sellerId,itemName:x.name,price:x.price,tax,shipping,sellerReceive:x.price-tax-shipping,code,status:"completed",createdAt:serverTimestamp()})});toast("購入完了",`取引コード：${code}<br>現物受け渡し時に提示してください。`);loadMarket()}catch(e){toast("購入できません",e.message)}}

function openListingModal(){state.activeModalItem=null;$("#modal-item-icon").textContent="＋";$("#modal-item-name").textContent="マーケットに出品";$("#modal-chart").style.display="none";$("#modal-item-price").style.display="none";$("#modal-buy-btn").style.display="none";$("#modal-error-msg").style.display="none";let old=$("#market-listing-form");if(old)old.remove();let f=document.createElement("div");f.id="market-listing-form";f.innerHTML=`<div class="listing-modal-grid"><label>画像（PNG/JPG/WEBP・5MB以下）<input id="listing-image" class="input-field" type="file" accept="image/png,image/jpeg,image/webp"></label><label>商品名<input id="listing-name" class="input-field" maxlength="80"></label><label>価格（$s）<input id="listing-price" class="input-field" type="number" min="1"></label><label>説明<textarea id="listing-desc" class="input-field"></textarea></label><label>ハッシュタグ<input id="listing-tags" class="input-field" placeholder="#ペンライト #レア #並木"></label><button id="submit-listing" class="btn" style="width:100%">出品する</button></div>`;$("#modal-box").appendChild(f);$("#shop-modal").style.display="flex";$("#submit-listing").onclick=submitListing}
async function submitListing(){let f=$("#listing-image").files[0],n=$("#listing-name").value.trim(),p=Math.floor(Number($("#listing-price").value));if(!f||!n||!p)return toast("入力不足","画像・商品名・価格を入力してください。");if(f.size>5*1024*1024)return toast("画像が大きすぎます","5MB以下にしてください。");try{let path=`market/${state.user.uid}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`,r=ref(storage,path);await uploadBytes(r,f,{contentType:f.type});let url=await getDownloadURL(r),tags=$("#listing-tags").value.split(/\s+/).filter(Boolean).map(x=>x.replace(/^#/,"")).slice(0,20);await addDoc(collection(db,"listings"),{sellerId:state.user.uid,sellerName:state.profile.displayName,name:n,price:p,description:$("#listing-desc").value.trim(),hashtags:tags,thumbnailUrl:url,storagePath:path,status:"active",createdAt:serverTimestamp()});closeShopModal();toast("出品完了","マーケットに掲載しました。");loadMarket()}catch(e){toast("出品できません",e.message)}}
$("#open-listing-modal")?.addEventListener("click",openListingModal);$("#market-search")?.addEventListener("input",renderMarket);$("#market-refresh")?.addEventListener("click",loadMarket);

function renderFXPosition(){let box=$("#fx-position"),p=state.fx.position;if(!box)return;if(!p){box.style.display="none";return}let mv=p.side==="buy"?state.fx.rate-p.entry:p.entry-state.fx.rate,pnl=Math.floor(mv/p.entry*p.stake*p.leverage),maint=Math.max(0,100+pnl/p.stake*100);box.style.display="block";box.innerHTML=`<strong>${p.side==="buy"?"▲ BUY":"▼ SELL"} ${p.leverage}x</strong><div>約定 ${p.entry.toFixed(3)} / 掛金 ${yen(p.stake)} $s</div><div class="${pnl>=0?"profit-plus":"profit-minus"}">含み損益：${pnl>=0?"+":""}${yen(pnl)} $s</div><div style="font-size:11px;color:var(--text-sub)">証拠金維持率の目安：${maint.toFixed(1)}%</div><div class="liq-warning">${maint<55?"⚠ ロスカット警戒：危険水準に近づいています。":"ロスカットラインまで余裕があります。"}</div><button class="btn" id="fx-close-position" style="width:100%;margin-top:9px">決済する</button>`;$("#fx-close-position").onclick=closeFXTrade}
window.selectLeverage=(v,e)=>{state.fx.leverage=v;document.querySelectorAll(".lev-btn").forEach(x=>x.classList.remove("active"));e.classList.add("active");$("#fx-leverage-display").textContent=v+"x";renderFXPosition()}
window.openFXTrade=side=>{let s=Math.floor(Number($("#fx-stake").value));if(state.fx.position)return toast("取引中","先に現在のポジションを決済してください。");if(!s||s<1)return toast("入力エラー","掛金を正しく入力してください。");if((state.profile?.balance||0)<s)return toast("取引エラー","$sが足りません。");state.fx.position={side,stake:s,entry:state.fx.rate,leverage:state.fx.leverage};renderFXPosition();toast("ポジション開始",`${side==="buy"?"買い":"売り"} / ${state.fx.leverage}x`)};
window.closeFXTrade=closeFXTrade;
async function closeFXTrade(){let p=state.fx.position;if(!p)return;let mv=p.side==="buy"?state.fx.rate-p.entry:p.entry-state.fx.rate,pnl=Math.floor(mv/p.entry*p.stake*p.leverage),pay=Math.max(0,p.stake+pnl);try{await updateDoc(doc(db,"users",state.user.uid),{balance:increment(pay)});await addDoc(collection(db,"fxTransactions"),{userId:state.user.uid,side:p.side,stake:p.stake,leverage:p.leverage,entry:p.entry,exit:state.fx.rate,pnl,payout:pay,createdAt:serverTimestamp()});state.profile.balance+=pay;state.fx.position=null;sync();toast("FX決済",`受取 ${yen(pay)} $s / 損益 ${pnl>=0?"+":""}${yen(pnl)} $s`)}catch(e){toast("決済エラー",e.message)}}
document.querySelectorAll("#leverage-row .lev-btn").forEach((b,i)=>b.addEventListener("click",()=>selectLeverage([2,4,6,10][i],b)));

async function verifyTradeCode(){let code=$("#trade-code-check").value.trim();if(!code)return;try{let q=await getDocs(query(collection(db,"transactions"),where("code","==",code),limit(1)));let o=$("#trade-code-result");if(q.empty){o.textContent="このコードは確認できません。";o.style.color="#ef7777";return}let d=q.docs[0].data();o.textContent=`✓ 正しい取引コードです。商品：${d.itemName||"商品"} / 金額：${yen(d.price)} $s / 状態：${d.status}`;o.style.color="#72d69a"}catch(e){toast("確認できません",e.message)}}
$("#verify-trade-code")?.addEventListener("click",verifyTradeCode);

window.openAccountPanel=()=>switchTab("account");window.openCollectionPanel=()=>switchTab("room");window.openAdminPanel=()=>switchTab("admin");window.openSettings=()=>$("#settings-modal").style.display="flex";window.closeSettings=()=>$("#settings-modal").style.display="none";
$("#save-account")?.addEventListener("click",async()=>{let n=$("#account-name-input").value.trim();if(!n)return;try{await updateDoc(doc(db,"users",state.user.uid),{displayName:n});state.profile.displayName=n;sync();toast("保存しました","表示名を更新しました。")}catch(e){toast("保存できません",e.message)}});

document.querySelectorAll(".admin-command").forEach(b=>b.onclick=()=>{if(state.profile?.status!=="admin")return toast("権限がありません","管理者のみ利用できます。");$("#admin-view").innerHTML=`<h3>${b.textContent}</h3><p class="settings-help">ここからFirebase上のユーザー・$s・在庫・通報・コード・銀行データを管理する管理機能を追加できます。</p>`});

window.login=async()=>{let email=$("#login-id").value.trim(),pass=$("#login-pass").value;if(!email||!pass)return toast("ログイン","メールアドレスとパスワードを入力してください。");try{await signInWithEmailAndPassword(auth,email,pass)}catch(e){toast("ログインできません","Firebase Authenticationの設定と入力を確認してください。")}};
window.logout=()=>signOut(auth);

onAuthStateChanged(auth,async u=>{state.user=u;if(!u){$("#login-screen").style.display="flex";return}$("#login-screen").style.display="none";await ensureProfile(u);renderNews();renderInventory();renderRoom();loadMarket()});

renderNews();initHistory();updatePrices();setInterval(tick,1000);
